#!/usr/bin/env ruby
# frozen_string_literal: true

# Writes tests/provenance.yaml - the corpus manifest (plurimath-testsuite
# parity). Records how every payload was produced (generator hash, oracle
# gem commit, ruby), and a sha256 + byte count per GENERATED payload so
# hand-edits are detectable. _status.yaml files are CURATED (hand-editable
# ledger state) and are listed as such, never hashed.
# Gem-free: runs with plain `ruby`.

require "yaml"
require "digest"
require "open3"

REPO = File.expand_path("..", __dir__)
GEM_DIR = ENV.fetch("PUBID_PATH", File.expand_path("../pubid", REPO))
CURATED = "_status.yaml"

def git_info(dir)
  commit, _ = Open3.capture2("git", "-C", dir, "rev-parse", "HEAD")
  status, _ = Open3.capture2("git", "-C", dir, "status", "--porcelain")
  dirty = status.split("\n").map { |l| l[3..].to_s.strip }.reject(&:empty?)
  { "commit" => commit.strip, "clean" => dirty.empty?, "dirty_paths" => dirty.first(20) }
rescue StandardError
  { "commit" => "unknown", "clean" => false, "dirty_paths" => [] }
end

def payload_entry(path, relative_to)
  { "path" => path.delete_prefix("#{relative_to}/"),
    "sha256" => Digest::SHA256.file(path).hexdigest,
    "bytes" => File.size(path) }
end

tests = File.join(REPO, "tests")
flavors = Dir[File.join(tests, "*")].select { |p| File.directory?(p) }.map { |p| File.basename(p) }.sort

generated = []
curated = []
flavors.each do |flavor|
  Dir[File.join(tests, flavor, "*.yaml")].sort.each do |path|
    rel = path.delete_prefix("#{tests}/")
    (File.basename(path) == CURATED ? curated : generated) << payload_entry(path, tests)
  end
end

counts = { "flavors" => flavors.size, "payloads" => generated.size + curated.size }
Dir[File.join(tests, "*", "*.yaml")].each do |path|
  name = File.basename(path)
  next if name.start_with?("_")
  YAML.safe_load_file(path).each do |doc|
    next unless doc.is_a?(Hash)
    counts["cases"] = counts["cases"].to_i + 1
    counts["aliases"] = counts["aliases"].to_i + Array(doc["non_normalized_aliases"]).size
  end
end
counts["negatives"] = Dir[File.join(tests, "*", "_negative.yaml")].sum do |path|
  YAML.safe_load_file(path).to_a.size
end

manifest = {
  "schema" => "pubid-tests/provenance/1",
  "generated_by" => "tools/provenance.rb - do not edit",
  "generator" => {
    "exporter" => "tools/export.rb",
    "exporter_sha256" => Digest::SHA256.file(File.join(REPO, "tools", "export.rb")).hexdigest,
  },
  "oracle" => { "gem" => "pubid" }.merge(git_info(GEM_DIR)),
  "repository" => git_info(REPO),
  "ruby" => { "version" => RUBY_VERSION },
  "counts" => counts,
  "payloads" => generated,
  "curated" => curated,
}

File.write(File.join(tests, "provenance.yaml"),
  "# Corpus provenance manifest. Generated by tools/provenance.rb; do not edit.\n" \
  "# Each payloads[].sha256 covers that whole file.\n" + YAML.dump(manifest))
puts "provenance: #{counts['flavors']} flavors, #{counts['payloads']} payloads " \
     "(#{generated.size} generated + #{curated.size} curated), #{counts['cases']} cases"
